SELECT
STVMAJR.STVMAJR_CODE major,
STVMAJR.STVMAJR_ACTIVITY_DATE recordActivityDate,
STVMAJR.STVMAJR_DESC majorDescription,
SORCMJR.SORCMJR_CURR_RULE curriculumRule,
SORCMJR.SORCMJR_TERM_CODE_EFF curriculumTermCodeEff,
STVMAJR.STVMAJR_CIPC_CODE cipCode,
STVCIPC.STVCIPC_DESC cipCodeDescription,
CASE
WHEN STVMAJR.STVMAJR_CODE IN ('ACCT','ANTH','MGMT','THEA','BIOL','CRIM','DENH','U101','CYBR','TSP','ONCO','ACTS') THEN 'True'
ELSE 'False'
END isDistanceEd,
'fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4' as tenantId,
'316' AS groupEntityExecutionId,
'65354417-dff9-40cf-ad8d-e7eb5c0b77ad' as userId,
'processed-data/fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4/20/2019-12-18 14:19:02' AS dataPath
FROM
SATURN.STVMAJR STVMAJR
LEFT JOIN SATURN.STVCIPC STVCIPC ON
STVMAJR.STVMAJR_CIPC_CODE = STVCIPC.STVCIPC_CODE
AND STVCIPC.STVCIPC_CIPC_A_IND = 'Y'
LEFT JOIN SATURN.SORCMJR SORCMJR ON
STVMAJR.STVMAJR_CODE = SORCMJR.SORCMJR_MAJR_CODE
AND SORCMJR.SORCMJR_HIS_IND = 'Y'
WHERE
STVMAJR.STVMAJR_VALID_MAJOR_IND = 'Y'
AND STVMAJR.STVMAJR_CIPC_CODE IS NOT NULL