SELECT
STVMAJR.STVMAJR_CODE major,
STVMAJR.STVMAJR_ACTIVITY_DATE recordActivityDate,
STVMAJR.STVMAJR_DESC majorDescription,
SORCMJR.SORCMJR_CURR_RULE curriculumRule,
SORCMJR.SORCMJR_TERM_CODE_EFF curriculumTermCodeEff,
STVMAJR.STVMAJR_CIPC_CODE cipCode,
STVCIPC.STVCIPC_DESC cipCodeDescription,
CASE
WHEN STVMAJR.STVMAJR_CODE IN ('ACCT','ANTH','MGMT') THEN 'True'
WHEN STVMAJR.STVMAJR_CODE IN ('THEA','BIOL','CRIM') THEN 'yes'
WHEN STVMAJR.STVMAJR_CODE IN ('DENH','U101','CYBR') THEN 'y'
WHEN STVMAJR.STVMAJR_CODE IN ('TSP','ONCO','ACTS') THEN 'true'
ELSE 'False'
END isDistanceEd

FROM
SATURN.STVMAJR STVMAJR
LEFT JOIN SATURN.STVCIPC STVCIPC ON
STVMAJR.STVMAJR_CIPC_CODE = STVCIPC.STVCIPC_CODE
AND STVCIPC.STVCIPC_CIPC_A_IND = 'Y'
LEFT JOIN SATURN.SORCMJR SORCMJR ON
STVMAJR.STVMAJR_CODE = SORCMJR.SORCMJR_MAJR_CODE
AND SORCMJR.SORCMJR_HIS_IND = 'Y'
WHERE
STVMAJR.STVMAJR_VALID_MAJOR_IND = 'Y'
AND STVMAJR.STVMAJR_CIPC_CODE IS NOT NULL
