SELECT
STVDEGC.STVDEGC_CODE AS degree,
CASE
WHEN STVDEGC.STVDEGC_CODE IN ('000000', 'NODEG') THEN 1
ELSE 0
END AS isNonDegreeSeeking,
STVDEGC.STVDEGC_ACTIVITY_DATE AS recordActivityDate,
STVDEGC.STVDEGC_DESC AS degreeDescription,
SOBCURR.SOBCURR_CURR_RULE AS curriculumRule,
SOBCURR.SOBCURR_TERM_CODE_INIT AS curriculumTermCodeInit,
STVDEGC.STVDEGC_ACAT_CODE AS acat,
STVACAT.STVACAT_DESC AS acatDescription
FROM SATURN.STVDEGC STVDEGC
LEFT JOIN SATURN.STVACAT STVACAT ON STVDEGC.STVDEGC_ACAT_CODE = STVACAT.STVACAT_CODE
LEFT JOIN SATURN.SOBCURR SOBCURR ON STVDEGC.STVDEGC_CODE = SOBCURR.SOBCURR_DEGC_CODE AND SOBCURR.SOBCURR_LOCK_IND = 'Y'