SELECT
  SHRDGMR.SHRDGMR_PIDM personId,
  SHRDGMR.SHRDGMR_ACTIVITY_DATE recordActivityDate,
  SHRDGMR.SHRDGMR_TERM_CODE_GRAD awardedTermCode,
  SHRDGMR.SHRDGMR_LEVL_CODE awardLevelRaw,
  SHRDGMR.SHRDGMR_DEGS_CODE awardStatusRaw,
  SHRDGMR.SHRDGMR_DEGC_CODE degree,
  SHRDGMR.SHRDGMR_GRAD_DATE awardedDate,
  SHRDGMR.SHRDGMR_COLL_CODE_1 college,
  null gpa,
  null classRank,
  SHRDGMR.SHRDGMR_CAMP_CODE campus
FROM SATURN.SHRDGMR SHRDGMR
WHERE SHRDGMR.SHRDGMR_GRAD_DATE IS NOT NULL