SELECT
 SHRDGMR.SHRDGMR_PIDM personId,
 TO_CHAR(CAST(SHRDGMR.SHRDGMR_ACTIVITY_DATE AS TIMESTAMP WITH TIME ZONE), 'MM/DD/YYYY HH24:MI:SS') AS recordActivityDate,
 SHRDGMR.SHRDGMR_TERM_CODE_GRAD awardedTermCode,
 CASE
 WHEN SHRDGMR.SHRDGMR_LEVL_CODE = 'PR' THEN 'Graduate'
 WHEN SHRDGMR.SHRDGMR_LEVL_CODE = 'RP' THEN 'Postgraduate'
 WHEN SHRDGMR.SHRDGMR_LEVL_CODE = 'GR' THEN 'Professional'
 WHEN SHRDGMR.SHRDGMR_LEVL_CODE = 'UG' THEN 'Continuing Ed'
 WHEN SHRDGMR.SHRDGMR_LEVL_CODE IN ('CE','LW','AP','CR','NC') THEN 'Undergrad'
 ELSE ''  END awardLevel,
 CASE
 WHEN SHRDGMR.SHRDGMR_DEGS_CODE = 'UP' THEN 'Awarded'
 WHEN SHRDGMR.SHRDGMR_DEGS_CODE IN ('SO','AW','GR','PN','AP') THEN 'Pending'
 ELSE ''  END awardStatus,
 SHRDGMR.SHRDGMR_DEGC_CODE degree,
 TO_CHAR(CAST(SHRDGMR.SHRDGMR_GRAD_DATE AS TIMESTAMP WITH TIME ZONE), 'MM/DD/YYYY HH24:MI:SS') AS awardedDate,
 null gpa,
 null classRank,
 SHRDGMR.SHRDGMR_CAMP_CODE campus,
 SHRDGMR.SHRDGMR_LEVL_CODE awardLevelRaw,
 SHRDGMR.SHRDGMR_DEGS_CODE awardStatusRaw,
 'fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4' as tenantId,
    	'278' AS groupEntityExecutionId,
	'65354417-dff9-40cf-ad8d-e7eb5c0b77ad' as userId,
	'processed-data/fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4/9/2019-12-17 10:31:59' AS dataPath
FROM SATURN.SHRDGMR SHRDGMR
WHERE SHRDGMR.SHRDGMR_GRAD_DATE IS NOT NULL
