select
  STVCAMP.STVCAMP_CODE campus,
  STVCAMP.STVCAMP_ACTIVITY_DATE recordActivityDate,
  STVCAMP.STVCAMP_DESC campusDescription,
  CASE WHEN LENGTH(STVCAMP.STVCAMP_CODE) > 2 THEN 1 ELSE 0 END isInternational
from SATURN.STVCAMP STVCAMP