SELECT 
  SSBSECT.SSBSECT_TERM_CODE termCode,
  SSBSECT.SSBSECT_PTRM_CODE partOfTerm,
  SSBSECT.SSBSECT_CRN crn,
  SSBSECT.SSBSECT_ACTIVITY_DATE recordActivityDate,
  SCBCRSE.SCBCRSE_TITLE title,
  SSBSECT.SSBSECT_INSM_CODE instructionMethod,
  SCBCRSE.SCBCRSE_SUBJ_CODE subject,
  SSBSECT.SSBSECT_CAMP_CODE campus,
  SCBCRSE.SCBCRSE_COLL_CODE college,
  SCBCRSE.SCBCRSE_DEPT_CODE department,
  SCBCRSE.SCBCRSE_CRSE_NUMB courseNumber,
  SSBSECT.SSBSECT_MAX_ENRL maxSeats,
  SCBCRSE.SCBCRSE_CREDIT_HR_HIGH creditHourHigh,
  SCBCRSE.SCBCRSE_CREDIT_HR_LOW creditHourLow,
  SCBCRSE.SCBCRSE_BILL_HR_HIGH billHourHigh,
  SCBCRSE.SCBCRSE_BILL_HR_LOW billHourLow,
  SCBCRSE.SCBCRSE_LEC_HR_HIGH lectureHourHigh,
  SCBCRSE.SCBCRSE_LEC_HR_LOW lectureHourLow,
  SCBCRSE.SCBCRSE_LAB_HR_HIGH labHourHigh,
  SCBCRSE.SCBCRSE_LAB_HR_LOW labHourLow
FROM SATURN.SSBSECT SSBSECT
INNER JOIN SATURN.SCBCRSE SCBCRSE
    ON SCBCRSE.SCBCRSE_SUBJ_CODE = SSBSECT.SSBSECT_SUBJ_CODE 
        AND SCBCRSE.SCBCRSE_CRSE_NUMB = SSBSECT.SSBSECT_CRSE_NUMB
        AND SCBCRSE.SCBCRSE_EFF_TERM = (SELECT MAX(SCBCRSE1.SCBCRSE_EFF_TERM)
                                        FROM SATURN.SCBCRSE SCBCRSE1
                                        WHERE SCBCRSE1.SCBCRSE_SUBJ_CODE = SCBCRSE.SCBCRSE_SUBJ_CODE
                                        AND SCBCRSE1.SCBCRSE_CRSE_NUMB = SCBCRSE.SCBCRSE_CRSE_NUMB
                                        AND SCBCRSE1.SCBCRSE_EFF_TERM <= SSBSECT.SSBSECT_TERM_CODE)