SELECT
  RPRATRM.RPRATRM_PIDM personId,
  RPRATRM.RPRATRM_ACTIVITY_DATE recordActivityDate,
  RPRATRM.RPRATRM_PERIOD termCode,
  RPRATRM.RPRATRM_AIDY_CODE financialAidYear,
  RFRBASE.RFRBASE_FTYP_CODE fundTypeRaw,
  RFRBASE.RFRBASE_FUND_CODE fundCode,
  RFRBASE.RFRBASE_FSRC_CODE fundSourceRaw,
  RPRATRM.RPRATRM_AWST_CODE awardStatusRaw,
  
 CASE WHEN RFRBASE.RFRBASE_FTYP_CODE = 'GRNT'
            AND RFRBASE.RFRBASE_FUND_CODE = 'PELL'
            AND RFRBASE.RFRBASE_FSRC_CODE = 'FDRL'THEN 1 ELSE 0 END isPellGrant,
            
 CASE WHEN RFRBASE.RFRBASE_FTYP_CODE IN ('GRNT', 'LOAN')
            AND RFRBASE.RFRBASE_FUND_CODE IN ('SEOG', 'ACG', 'SMRT', 'TEACH', 'PERK', 'DIRECT', 'DLUNSB', 'STFD', 'STFDB', 'UNSTFD', 'PELL')
            AND RFRBASE.RFRBASE_FSRC_CODE = 'FDRL' THEN 1 ELSE 0 END isTitleIV,
            
 CASE WHEN RFRBASE.RFRBASE_FTYP_CODE = 'LOAN'
            AND RFRBASE.RFRBASE_FUND_CODE = 'DIRECT'
            AND RFRBASE.RFRBASE_FSRC_CODE = 'FDRL' THEN 1 ELSE 0 END isSubsidizedDirectLoan,
            
  RPRATRM.RPRATRM_ACCEPT_AMT acceptedAmount,
  RPRATRM.RPRATRM_OFFER_AMT offeredAmount,
  RPRATRM.RPRATRM_PAID_AMT paidAmount,
  
 CASE WHEN RFRBASE.RFRBASE_FTYP_CODE = 'LOAN' THEN RPRATRM.RPRATRM_ACCEPT_AMT
      ELSE RPRATRM.RPRATRM_OFFER_AMT
 END IPEDSReportableAmount,
  
 (SELECT ROUND(SUM(RCRAPP4.RCRAPP4_FISAP_INC),2)
  FROM FAISMGR.RCRAPP4 RCRAPP4
 INNER JOIN FAISMGR.RCRAPP1 RCRAPP1 ON RCRAPP1.RCRAPP1_AIDY_CODE = RCRAPP4.RCRAPP4_AIDY_CODE
  AND RCRAPP1.RCRAPP1_PIDM = RCRAPP4.RCRAPP4_PIDM
  AND RCRAPP1.RCRAPP1_SEQ_NO = RCRAPP4.RCRAPP4_SEQ_NO
 WHERE RCRAPP1.RCRAPP1_PIDM = RPRATRM.RPRATRM_PIDM 
  AND RCRAPP1.RCRAPP1_CURR_REC_IND ='Y'
  AND RCRAPP1.RCRAPP1_AIDY_CODE = (SELECT MAX(RCRAPP1_1.RCRAPP1_AIDY_CODE) 
                                   FROM FAISMGR.RCRAPP1 RCRAPP1_1
                                   WHERE RCRAPP1_1.RCRAPP1_PIDM = RCRAPP1.RCRAPP1_PIDM
                                      AND RCRAPP1_1.RCRAPP1_AIDY_CODE <= RPRATRM.RPRATRM_AIDY_CODE
                                      AND RCRAPP1_1.RCRAPP1_CURR_REC_IND ='Y' ) )  familyIncome,
                                           
 (SELECT RORSTAT.RORSTAT_BGRP_CODE
  FROM FAISMGR.RORSTAT RORSTAT
  INNER JOIN FAISMGR.RCRAPP1 RCRAPP1_2
    ON RCRAPP1_2.RCRAPP1_PIDM = RORSTAT.RORSTAT_PIDM 
    AND RCRAPP1_2.RCRAPP1_AIDY_CODE = RORSTAT.RORSTAT_AIDY_CODE
    AND RCRAPP1_2.RCRAPP1_CURR_REC_IND ='Y'
    AND RCRAPP1_2.RCRAPP1_AIDY_CODE = (SELECT MAX(RCRAPP1_3.RCRAPP1_AIDY_CODE) 
                                       FROM FAISMGR.RCRAPP1 RCRAPP1_3
                                       WHERE RCRAPP1_3.RCRAPP1_PIDM = RCRAPP1_2.RCRAPP1_PIDM
                                         AND RCRAPP1_3.RCRAPP1_AIDY_CODE <= RPRATRM.RPRATRM_AIDY_CODE
                                         AND  RCRAPP1_3.RCRAPP1_CURR_REC_IND ='Y')
  WHERE RORSTAT.RORSTAT_PIDM = RPRATRM.RPRATRM_PIDM ) livingArrangementRaw,
  1 isIPEDSReportable
                                           
FROM FAISMGR.RPRATRM RPRATRM
LEFT JOIN FAISMGR.RFRBASE RFRBASE ON RPRATRM.RPRATRM_FUND_CODE = RFRBASE.RFRBASE_FUND_CODE
         and RFRBASE.RFRBASE_FTYP_CODE IS NOT NULL
         and RFRBASE.RFRBASE_FSRC_CODE IS NOT NULL