SELECT
 SORLCUR.SORLCUR_PIDM personID,
 SORLCUR.SORLCUR_TERM_CODE termCodeEffective,
 SORLCUR.SORLCUR_ACTIVITY_DATE recordActivityDate,
 SORLFOS.SORLFOS_PRIORITY_NO fieldOfStudyPriority,
 CASE
   WHEN SORLFOS.SORLFOS_LFST_CODE = 'MAJOR' THEN 'Major'
   WHEN SORLFOS.SORLFOS_LFST_CODE = 'CERTIFICATION' THEN 'Certification'
   WHEN SORLFOS.SORLFOS_LFST_CODE = 'CONCENTRATION' THEN 'Concentration'
   ELSE '' END fieldOfStudyType,

 SORLFOS.SORLFOS_MAJR_CODE curriculumCode,
 SORLCUR.SORLCUR_DEGC_CODE degree,
 SORLCUR.SORLCUR_COLL_CODE college,
 CASE
 WHEN SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE = 'COMPLETED_ADMISSIONS' THEN 'Completed'
 WHEN SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE = 'SOUGHT_OUTCOME' THEN 'In Progress'
 WHEN SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE = 'DENIED_ADMISSIONS' THEN 'Applied'
 ELSE '' END curriculumStatus,

 CASE
 WHEN SORLCUR.SORLCUR_LEVL_CODE = 'HS' THEN 'Undergrad'
 WHEN SORLCUR.SORLCUR_LEVL_CODE = 'GD' THEN 'Graduate'
 WHEN SORLCUR.SORLCUR_LEVL_CODE = 'ED' THEN 'Postgraduate'
 ELSE '' END academicTrackLevel,
   'True' isIPEDSReportable,
 SORLFOS.SORLFOS_LFST_CODE fieldOfStudyTypeRaw,
 SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE curriculumStatusRaw,
 SORLCUR.SORLCUR_LEVL_CODE academicTrackLevelRaw,
 'fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4' as tenantId,
    	'229' AS groupEntityExecutionId,
	'65354417-dff9-40cf-ad8d-e7eb5c0b77ad' as userId,
	'processed-data/fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4/7/2019-12-16 15:51:51' AS dataPath
FROM SATURN.SORLCUR SORLCUR
INNER JOIN SATURN.SORLFOS SORLFOS on SORLCUR.SORLCUR_PIDM = SORLFOS.SORLFOS_PIDM
     AND SORLCUR.SORLCUR_TERM_CODE = SORLFOS.SORLFOS_TERM_CODE
     AND SORLCUR.SORLCUR_SEQNO = SORLFOS.SORLFOS_LCUR_SEQNO
     AND SORLFOS.SORLFOS_CACT_CODE = 'ACTIVE'
WHERE SORLCUR.SORLCUR_CACT_CODE = 'ACTIVE'
UNION
SELECT
 SORLCUR.SORLCUR_PIDM personID,
 SORLFOS.SORLFOS_TERM_CODE termCodeEffective,
 SORLFOS.SORLFOS_ACTIVITY_DATE recordActivityDate,
 SORLFOS.SORLFOS_PRIORITY_NO fieldOfStudyPriority,
 CASE
   WHEN SORLFOS.SORLFOS_LFST_CODE = 'MAJOR' THEN 'Major'
   WHEN SORLFOS.SORLFOS_LFST_CODE = 'CERTIFICATION' THEN 'Certification'
   WHEN SORLFOS.SORLFOS_LFST_CODE = 'CONCENTRATION' THEN 'Concentration'
   ELSE '' END fieldOfStudyType,

 SORLFOS.SORLFOS_MAJR_CODE curriculumCode,
 SORLCUR.SORLCUR_DEGC_CODE degree,
 SORLCUR.SORLCUR_COLL_CODE college,
 CASE
 WHEN SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE = 'COMPLETED_ADMISSIONS' THEN 'Completed'
 WHEN SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE = 'SOUGHT_OUTCOME' THEN 'In Progress'
 WHEN SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE = 'DENIED_ADMISSIONS' THEN 'Applied'
 ELSE '' END curriculumStatus,
 CASE
 WHEN SORLCUR.SORLCUR_LEVL_CODE = 'HS' THEN 'Undergrad'
 WHEN SORLCUR.SORLCUR_LEVL_CODE = 'GD' THEN 'Graduate'
 WHEN SORLCUR.SORLCUR_LEVL_CODE = 'ED' THEN 'Postgraduate'
 ELSE '' END academicTrackLevel,
    'True' isIPEDSReportable,
 SORLFOS.SORLFOS_LFST_CODE fieldOfStudyTypeRaw,
 SORLFOS.SORLFOS_CSTS_CODE || '_' || SORLCUR.SORLCUR_LMOD_CODE curriculumStatusRaw,
 SORLCUR.SORLCUR_LEVL_CODE academicTrackLevelRaw,
 'fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4' as tenantId,
    	'229' AS groupEntityExecutionId,
	'65354417-dff9-40cf-ad8d-e7eb5c0b77ad' as userId,
	'processed-data/fa748ab4-a958-11e9-a2a3-2a2ae2dbcce4/7/2019-12-16 15:51:51' AS dataPath
FROM SATURN.SORLCUR SORLCUR
INNER JOIN SATURN.SORLFOS SORLFOS on SORLCUR.SORLCUR_PIDM = SORLFOS.SORLFOS_PIDM
     AND SORLCUR.SORLCUR_TERM_CODE = SORLFOS.SORLFOS_TERM_CODE
     AND SORLCUR.SORLCUR_SEQNO = SORLFOS.SORLFOS_LCUR_SEQNO
     AND SORLFOS.SORLFOS_CACT_CODE = 'ACTIVE'
WHERE SORLCUR.SORLCUR_CACT_CODE = 'ACTIVE'
