select * from (select
  SORTEST.SORTEST_PIDM personId,
  TO_CHAR(CAST(SORTEST.SORTEST_ACTIVITY_DATE AS TIMESTAMP WITH TIME ZONE), 'MM/DD/YYYY HH24:MI:SS') AS recordActivityDate,
  SORTEST.SORTEST_TEST_SCORE testScore,
  SORTEST.SORTEST_TESC_CODE testScoreTypeRaw,
  TO_CHAR(CAST(SORTEST.SORTEST_TEST_DATE AS TIMESTAMP WITH TIME ZONE), 'MM/DD/YYYY HH24:MI:SS') AS testDate
from SATURN.SORTEST SORTEST
order by SORTEST.SORTEST_PIDM,
         SORTEST.SORTEST_ACTIVITY_DATE)
         where testDate not in ('03/10/1000 00:00:00', '02/14/0011 00:00:00')