SELECT
  SSBSECT.SSBSECT_TERM_CODE termCode,
  SSBSECT.SSBSECT_PTRM_CODE partOfTerm,
  SSBSECT.SSBSECT_CRN crn,
  SSRMEET.SSRMEET_CATAGORY section,
  CASE
    WHEN SSRMEET.SSRMEET_MTYP_CODE IN ('WEB', 'VIRT')
        OR SSRMEET.SSRMEET_SCHD_CODE IN ('COR', 'WLB', 'WLP', 'D')
        OR SSBSECT.SSBSECT_INSM_CODE IN ('WEB', 'DLEAR', 'WLB') THEN 'True'
    ELSE 'False'
  END isDistanceEd,
  SSRMEET.SSRMEET_ACTIVITY_DATE recordActivityDate,
  SSRMEET.SSRMEET_BLDG_CODE building,
  SSRMEET.SSRMEET_ROOM_CODE room,
  SSRMEET.SSRMEET_START_DATE startDate,
  SSRMEET.SSRMEET_END_DATE endDate,
  SSRMEET.SSRMEET_BEGIN_TIME startTime,
  SSRMEET.SSRMEET_END_TIME endTime,
  CASE
    WHEN coalesce(SSRMEET.SSRMEET_SUN_DAY, SSRMEET.SSRMEET_MON_DAY, SSRMEET.SSRMEET_TUE_DAY, SSRMEET.SSRMEET_WED_DAY, SSRMEET.SSRMEET_THU_DAY, SSRMEET.SSRMEET_FRI_DAY, SSRMEET.SSRMEET_SAT_DAY) = 'W' THEN 'Monday'
    ELSE '' END dayOfWeek,
  SSRMEET.SSRMEET_CREDIT_HR_SESS creditHours,
  CASE
    WHEN nvl(STVSCHD.STVSCHD_DESC, GTVMTYP.GTVMTYP_DESC) = 'Internship/Coop' THEN 'On Campus Lecture'
    ELSE '' END meetingType,
  'True' isIPEDSReportable,
  coalesce(SSRMEET.SSRMEET_SUN_DAY, SSRMEET.SSRMEET_MON_DAY, SSRMEET.SSRMEET_TUE_DAY, SSRMEET.SSRMEET_WED_DAY, SSRMEET.SSRMEET_THU_DAY, SSRMEET.SSRMEET_FRI_DAY, SSRMEET.SSRMEET_SAT_DAY) dayOfWeekRaw,
  nvl(STVSCHD.STVSCHD_DESC, GTVMTYP.GTVMTYP_DESC) meetingTypeRaw,
  '37ae73e1-cbb3-4250-bfc2-54343450f1af' as tenantId,
      	'762' AS groupEntityExecutionId,
  	'09469017-73fe-4421-a352-d76d42e8f89f' as userId,
  	'processed-data/37ae73e1-cbb3-4250-bfc2-54343450f1af/14/2019-12-18 13:41:55' AS dataPath
FROM SATURN.SSBSECT SSBSECT
INNER JOIN SATURN.SSRMEET SSRMEET
    ON SSBSECT.SSBSECT_TERM_CODE = SSRMEET.SSRMEET_TERM_CODE
        AND (SSBSECT.SSBSECT_CRN = SSRMEET.SSRMEET_CRN)
        AND SSRMEET.SSRMEET_MTYP_CODE != 'EXAM'
LEFT JOIN SATURN.STVSCHD STVSCHD ON SSRMEET.SSRMEET_SCHD_CODE = STVSCHD.STVSCHD_CODE
LEFT JOIN GENERAL.GTVMTYP GTVMTYP ON SSRMEET.SSRMEET_MTYP_CODE = GTVMTYP.GTVMTYP_CODE
