select distinct
  PEBEMPL.PEBEMPL_PIDM personId,
  PEBEMPL.PEBEMPL_ACTIVITY_DATE recordActivityDate,
  PEBEMPL.PEBEMPL_CURRENT_HIRE_DATE hireDate,
  PEBEMPL.PEBEMPL_TERM_DATE terminationDate,
  PEBEMPL.PEBEMPL_INTERNAL_FT_PT_IND fullOrPartTimeStatusRaw,
  PEBEMPL.PEBEMPL_IPEDS_PRIMARY_FUNCTION IPEDSPrimaryFunctionRaw,
  case when PEBEMPL.PEBEMPL_IPEDS_PRIMARY_FUNCTION = 'GAT' then 1
            when PEBEMPL.PEBEMPL_ECLS_CODE IN ('GR', '19') then 1 else 0 end isGraduateAssistant,
  case when PEBEMPL.PEBEMPL_IPEDS_MED_DENTAL_IND = 'Y' then 1 else 0 end isIPEDSMedicalOrDental,
  PEBEMPL.PEBEMPL_EMPL_STATUS employeeStatusRaw,
  PEBEMPL.PEBEMPL_ECLS_CODE employeeClass,
  (select PTRECLS.PTRECLS_SHORT_DESC
  from PAYROLL.PTRECLS PTRECLS
  where PTRECLS.PTRECLS_CODE = PEBEMPL.PEBEMPL_ECLS_CODE) employeeClassDescription,
  PEBEMPL.PEBEMPL_EGRP_CODE employeeGroup,
  (select PTVEGRP.PTVEGRP_DESC
  from PAYROLL.PTVEGRP PTVEGRP
  where PTVEGRP.PTVEGRP_CODE = PEBEMPL.PEBEMPL_EGRP_CODE) employeeGroupDescription
from PAYROLL.PEBEMPL PEBEMPL
