SELECT
  SGRCHRT_PIDM personId,
  SGRCHRT_ACTIVITY_DATE recordActivityDate,
  SGRCHRT_TERM_CODE_EFF termCodeEffective,
  SGRCHRT_CREA_CODE exclusionReasonRaw,
  STVCREA_DESC exclusionReasonDescription
FROM SATURN.SGRCHRT
LEFT JOIN SATURN.STVCREA on SGRCHRT_CREA_CODE = STVCREA_CODE
WHERE SGRCHRT_ACTIVE_IND = 'Y'

UNION

SELECT
  SHRTTRM_PIDM personId,
  SHRTTRM_ACTIVITY_DATE recordActivityDate,
  SHRTTRM_TERM_CODE termCodeEffective,
  SHRTTRM_WRSN_CODE exclusionReasonRaw,
  STVWRSN_DESC exclusionReasonDescription
FROM SATURN.SHRTTRM
INNER JOIN SATURN.STVWRSN ON SHRTTRM_WRSN_CODE = STVWRSN_CODE